# Generated by Django 4.2.2 on 2023-08-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='todo',
        ),
    ]
