# Generated by Django 4.2.2 on 2023-08-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_text_todo_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='text',
        ),
    ]
